# Generated by Django 5.0.6 on 2024-05-23 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_smart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='longitutde',
            new_name='longitude',
        ),
    ]
